import type Database from 'better-sqlite3';
import type { MycoStatements, ClassificationResult } from '@myco/core';
import { embedText } from './embed-client.js';

/**
 * Distance thresholds for classification.
 *
 * sqlite-vec uses Euclidean distance between normalized (unit) vectors.
 * For unit vectors: euclidean_dist = sqrt(2 * cosine_dist), so:
 *   cosine_dist 0.08  → euclidean ~0.40  (NOOP boundary)
 *   cosine_dist 0.35  → euclidean ~0.84  (UPDATE/ADD boundary)
 *
 * - distance < NOOP_THRESHOLD: near-duplicate, skip write
 * - distance >= NOOP_THRESHOLD AND < UPDATE_THRESHOLD: related/conflicting, supersede
 * - distance >= UPDATE_THRESHOLD: different topic, add as new fact
 */
const NOOP_THRESHOLD = 0.40;
const UPDATE_THRESHOLD = 0.84;

/**
 * Classify an incoming observation against existing observations for the same entity.
 *
 * Returns ADD, UPDATE, or NOOP:
 * - ADD: No semantic overlap with existing facts — safe to insert as a new observation
 * - UPDATE: Supersedes an existing observation — caller should retire the old one then insert
 * - NOOP: Near-duplicate — skip write to avoid noise
 *
 * Timestamps MUST be generated by the caller before calling this function.
 * Do NOT use SQLite's CURRENT_TIMESTAMP.
 */
export async function classifyObservation(
  db: Database.Database,
  stmts: MycoStatements,
  entityId: string,
  content: string,
): Promise<ClassificationResult> {
  // Step 1: Fetch current (non-retired) observations for entity
  const existing = stmts.selectObservationsByEntityForDedup.all(entityId) as Array<{
    id: string;
    content: string;
    confidence: number;
    valid_from: string | null;
    valid_until: string | null;
  }>;

  if (existing.length === 0) {
    return {
      classification: 'ADD',
      reason: 'No existing observations for entity',
    };
  }

  // Step 2: Embed the new content
  const embedding = await embedText(content);

  // Step 3: Ollama unavailable — fall back to exact string match
  if (embedding === null) {
    const exactMatch = existing.find(obs => obs.content === content);
    if (exactMatch) {
      return {
        classification: 'NOOP',
        reason: 'exact string match (Ollama unavailable)',
      };
    }
    return {
      classification: 'ADD',
      reason: 'No exact match found (Ollama unavailable, safe default)',
    };
  }

  // Step 4: Use knnSearchForContradiction to find closest existing observation for this entity
  const vec = new Float32Array(embedding);
  const closest = stmts.knnSearchForContradiction.get(vec, entityId) as
    | { distance: number }
    | undefined;

  if (closest === undefined) {
    // No embedding found for any existing observation of this entity — treat as ADD
    return {
      classification: 'ADD',
      reason: 'No embeddings found for existing observations',
    };
  }

  const { distance } = closest;

  // Step 5: Apply thresholds
  if (distance < NOOP_THRESHOLD) {
    return {
      classification: 'NOOP',
      reason: `Near-duplicate (distance: ${distance.toFixed(4)})`,
    };
  }

  if (distance < UPDATE_THRESHOLD) {
    // Find the specific observation to supersede via a targeted query
    const supersededId = findClosestObservationId(db, vec, entityId);
    return {
      classification: 'UPDATE',
      superseded_observation_id: supersededId ?? undefined,
      reason: `Supersedes existing observation (distance: ${distance.toFixed(4)})`,
    };
  }

  return {
    classification: 'ADD',
    reason: `New fact — different topic (distance: ${distance.toFixed(4)})`,
  };
}

/**
 * Find the item_id of the closest existing observation embedding for a given entity.
 * Used in the UPDATE case to identify which observation should be retired.
 */
function findClosestObservationId(
  db: Database.Database,
  vec: Float32Array,
  entityId: string,
): string | null {
  const row = db
    .prepare(
      `WITH knn AS (
         SELECT item_id, distance FROM vec_embeddings
         WHERE embedding MATCH ? AND k = 5 AND item_type = 'observation'
       )
       SELECT knn.item_id FROM knn
       JOIN observations o ON o.id = knn.item_id
       WHERE o.entity_id = ? AND o.valid_until IS NULL
       ORDER BY knn.distance
       LIMIT 1`,
    )
    .get(vec, entityId) as { item_id: string } | undefined;

  return row?.item_id ?? null;
}

/**
 * Soft-retire an observation by setting valid_until.
 * The observation row is NOT deleted — it remains for historical queries.
 *
 * @param retiredAt ISO 8601 timestamp — caller provides, generated in application code
 */
export function retireObservation(
  stmts: MycoStatements,
  observationId: string,
  retiredAt: string,
): void {
  stmts.retireObservation.run(retiredAt, observationId);
}
